client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Home:index }

client_blog:
    path:     /blog
    defaults: { _controller: ClientBundle:Blog:index }

client_contact:
    path:     /contact
    defaults: { _controller: ClientBundle:Contact:index }
